MAIN=

CXXFLAGS=-Wall -Wextra -Wno-sign-compare -Wno-unused-result -std=c++11 -g -D_GLIBCXX_DEBUG
#CXXFLAGS=-Wall -Wextra -Wno-sign-compare -Wno-unused-result -std=c++11 -O2

all: $(MAIN)
clean:
	find . -maxdepth 1 -type f -perm -111 -delete
run: $(MAIN)
	./$< <$(MAIN).in
